### ISSUE TITLE
Data base on drizzle studio cant access

### ISSUE THREAD

**Issue by popcake456** [sanidhyy/duolingo-clone#11]
**Describe the bug**
after doing the steps till the end ... i tried to access it using drizzle kit studio... but it says on terminal it needs to be updated and when i run the update install of drizzle kit studio even if it is up to date ... it still say it need to be update

**To Reproduce**
1. do all the steps
2. run drizzle kit studio
3. it will say update your drizzle kit studio
4. update drizzle kit studio
5. it will still say it need to be update
6. i tried 0.20.0 drizzle kit studio
7. but it says "url"  or "host", "database" are required for database connection

**Expected behavior**
3 of language doesnt load after doing all the steps to guide due to drizzle kit not updated

**Desktop (please complete the following information):**
 - OS:Ryzen 3400g
 - Browser opera gx

**Additional context**
thank you good sir since you really help me for my capstone T^T i only downgraded the version since i saw 0.20.0 version working from others

**Comment by sanidhyy** [comment]
Hi!

It seems like you're encountering a problem with Drizzle Kit Studio's update process. A few users have also reported similar behavior. Here's what you can try:

1. **Clear any cached or previous installs** of Drizzle Kit Studio. Sometimes, remnants of previous versions may cause conflicts. You can try uninstalling and reinstalling it cleanly.

2. **Manually verify your version** by running `drizzle --version` in the terminal to make sure you're on the latest one.

3. **Check your configuration**: The error regarding "url", "host", and "database" suggests that Drizzle Kit Studio might not be receiving the correct connection parameters. Ensure that these are properly set in your environment variables or connection configuration.

4. **Try downgrading**: Since you mentioned that version 0.20.0 worked for others, temporarily downgrading might be a good workaround until the update issue is resolved.

Also, could you please share **screenshots** of the terminal or error messages you're seeing after attempting the update? This will help us better understand and troubleshoot the issue.
