### ISSUE TITLE
challenge practice to get hearts doesnt show the pictures

### ISSUE THREAD

**Issue by popcake456** [sanidhyy/duolingo-clone#23]
**Describe the bug**

**To Reproduce**
1. Go to Learn page
2. Click on 'past progress'
4. See error , where the pictures doesnt show

**Expected behavior**
it should show the picture

**Screenshots**
![image](https://github.com/user-attachments/assets/8f90ac88-85bd-444f-9603-8a3a1c788cf1)
![image](https://github.com/user-attachments/assets/9dc59e83-a08a-414c-bacd-1abe69f6e394)

**details**
 ⨯ node_modules\@clerk\nextjs\dist\esm\server\createGetAuth.js (26:0) @ eval
 ⨯ Error: Clerk: auth() was called but Clerk can't detect usage of authMiddleware(). Please ensure the following:
- authMiddleware() is used in your Next.js Middleware.
- Your Middleware matcher is configured to match this route or page.
- If you are using the src directory, make sure the Middleware file is inside of it.

For more details, see https://clerk.com/docs/quickstarts/nextjs

    at eval (./db/queries.ts:148:75)
    at LessonIdPage (./app/lesson/[lessonId]/page.tsx:15:78)
    at stringify (<anonymous>)
digest: "1025954684"
null

**Comment by sanidhyy** [comment]
Thank you for reporting this issue! It seems to be related to the `authMiddleware()` configuration with Clerk in your Next.js project. Here’s how we can address it step-by-step:

---

### **Steps to Debug and Fix**

#### **1. Verify Middleware Setup**
Ensure `authMiddleware()` is correctly implemented in the `middleware.ts` file. Here’s an example:

```typescript
import { authMiddleware } from "@clerk/nextjs";

export default authMiddleware({
  publicRoutes: ["/", "/learn", "/about"], // Add routes that don't require authentication
});

export const config = {
  matcher: ["/((?!_next/static|_next/image|favicon.ico).*)"], // Matches all routes except static assets
};
```

#### **2. Middleware File Location**
If you’re using the `src` directory, make sure the `middleware.ts` file is located at:
```
src/middleware.ts
```
This ensures the middleware is detected correctly by Next.js.

#### **3. Configure Matching Routes**
Double-check that the `matcher` includes the `/lesson/[lessonId]` route. If it’s excluded, authentication middleware won’t apply to that page.

#### **4. Initialize Clerk Properly**
Confirm that Clerk is initialized in your `_app.tsx` or `_app.js` file. Example:

```typescript
import { ClerkProvider } from "@clerk/nextjs";

function MyApp({ Component, pageProps }) {
  return (
    <ClerkProvider>
      <Component {...pageProps} />
    </ClerkProvider>
  );
}

export default MyApp;
```

#### **5. Fix Backend Queries**
From the error trace (`./db/queries.ts:148:75`), it seems a backend query uses `auth()`, which is failing due to the middleware issue. Instead, ensure `auth()` is used only after proper middleware setup or switch to:

```typescript
import { currentUser } from "@clerk/nextjs/server";

const user = await currentUser();
if (!user) throw new Error("User not authenticated");
```

#### **6. Resolve Missing Pictures**
The issue with pictures not showing could be unrelated to Clerk. Please check:
- Are the image URLs correct and accessible?
- Is the database or API returning valid paths for the images?
- Are any permissions blocking the images?

---

### **Next Steps**
1. Apply the fixes above and retest.
2. Refer to Clerk’s middleware documentation for additional details: [[Clerk Middleware Docs](https://clerk.com/docs/quickstarts/nextjs)](https://clerk.com/docs/quickstarts/nextjs).
3. Add logging to debug the `auth()` function:
   ```typescript
   import { auth } from "@clerk/nextjs";

   const user = auth();
   console.log(user);
   ```

Let me know if this helps or if you need further assistance! 😊

**Comment by popcake456** [comment]
sadly didnt worked this time .. after downloaded your app and do everystep .. the app works and everyhting that is intended works ... its just that if you need hearts you need to access past quiz and if you access the past on your app it doesnt show the pictures only words

**Comment by popcake456** [comment]
bug not fixed :(

**Comment by sanidhyy** [comment]
Are you using any custom images?

**Comment by popcake456** [comment]
i uploaded an svg files on public  .... for example tagalog.svg and more

**Comment by sanidhyy** [comment]
Can you set it again to default values and see what you get?

**Comment by popcake456** [comment]
should i delete the uploaded svg?

**Comment by popcake456** [comment]
sHould i delete the the new uploaded svg on my public? since thats the only thing i did and didnt change your code

**Comment by sanidhyy** [comment]
Did you not update in database when created new data.

**Comment by popcake456** [comment]
how do you update it in data base ? the thing we did was after uploading the image.svg we push the files to github then we put it up in website using vercel then we linked a questions and pictures and challenges on the adminpag....  ___.vercel.app/admin

**Comment by sanidhyy** [comment]
Yeh! Means same. Can you share new challenges options you added?

**Comment by popcake456** [comment]
![image](https://github.com/user-attachments/assets/91add205-5ed6-40c6-b399-43d6e05d1a16)
![image](https://github.com/user-attachments/assets/1abca2e4-508c-445c-9303-4fafd244af43)
since we uploaded the file with the svg on public  to github .. we just link it using that

**Comment by popcake456** [comment]
do you have discord? i can live it for easier communication

**Comment by sanidhyy** [comment]
Sure. My username is 'sanidhyy'.

**Comment by popcake456** [comment]
friend request sent ign was slime username was killua03

**Comment by popcake456** [comment]
![image](https://github.com/user-attachments/assets/91d637de-1ff8-40b6-b4be-29e7ee268eae)
discord said you need to accept my friend first
